name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libboost-all-dev redis-server libhiredis-dev  # 假设 Redis 用 hiredis；调整为你的依赖
        sudo apt-get install -y nlohmann-json3-dev
    - name: Clean build directory
      run: rm -rf build

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Run Tests
      working-directory: build
      run: ctest -C Release -V  # 假设你用 CTest；否则替换为你的 test.sh
